say:
  self: {}

  lint:
    do: "buf lint proto"

  build:
    rulemap:
      browser:
        platform: browser
        priority: -1
        stop: true
        cmds:
          - do: "pnpm --dir packages run build"

  test:
    rulemap:
      browser:
        platform: browser
        priority: -1
        stop: true
        cmds:
          - do: "pnpm --dir packages run test"

  launch:
    rulemap:
      browser:
        platform: browser
        priority: -1
        stop: true
        cmds:
          - do: "pnpm --dir packages/mecha-browser run dev"
      dapr:
        platform: local
        priority: -1
        stop: true
        cmds:
          - do: "dapr run -f dapr.yaml"

  integrate:
    rulemap:
      browser:
        platform: browser
        priority: -1
        stop: true
        cmds:
          - do: "pnpm --dir packages/mecha-browser run test"
