apiVersion: dapr.io/v1alpha1
kind: HTTPEndpoint
metadata:
  name: crud-service
spec:
  baseUrl: http://crud:3000
  headers:
    - name: Content-Type
      value: application/json
    - name: Accept
      value: application/json
---
apiVersion: dapr.io/v1alpha1
kind: HTTPEndpoint
metadata:
  name: proxy-service
spec:
  baseUrl: http://caddy:8080
  headers:
    - name: Content-Type
      value: application/json
